const menu = [
  {
    id: 1,
    title: "Poha Rice",
    category: "breakfast",
    price: "₹ 40.00",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/poha-recipe.jpg",
    desc: `This simple dish does not need any accompaniment. But it is usually garnished and topped with various ingredients.`,
  },

  {
    id: 21,
    title: "Chana Kulcha",
    category: "lunch",
    price: "₹ 70.00",
    img: "https://i.ndtvimg.com/i/2015-04/chana-kulcha_625x350_41429707001.jpg",
    desc: `A classic dish that never goes out of style. Made of ginger carom powder and some mango powder to give sour and tangy taste.`,
  },
  {
    id: 3,
    title: "Ice creamy chocolaty",
    category: "shakes",
    price: "₹ 70.00",
    img: "https://i2-prod.glasgowlive.co.uk/incoming/article16335490.ece/ALTERNATES/s810/0_DSC_5334-copy-1.jpg",
    desc: `A dreamy, chocolate-y, frothy milkshake made with a generous helping of chocolate ice cream, fragrant vanilla essence and a sprinkle of malt powder.`,
  },
  {
    id: 4,
    title: "Overnight Oats",
    category: "breakfast",
    price: "₹ 45.00",
    img: "https://www.vegrecipesofindia.com/wp-content/uploads/2016/06/overnight-oats.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "Allahabad Tehri",
    category: "lunch",
    price: "₹ 110.00",
    img: "https://i.ndtvimg.com/i/2015-04/pulao_625x350_51429707247.jpg",
    desc: `It's aromatic, made with a lot of bright vegetables, fiery masalas and topped with desi ghee.`,
  },
  {
    id: 6,
    title: "Almond Saffron",
    category: "shakes",
    price: "₹ 60.00",
    img: "https://i.ndtvimg.com/i/2016-11/m_620x350_51480077599.jpg",
    desc: `Almonds, walnuts and flax seeds make this milkshake extremely nutritious and a great pre workout drink. It'll give you an instant energy .`,
  },
  {
    id: 7,
    title: "Aloo Paratha",
    category: "breakfast",
    price: "₹ 25.00",
    img: "https://i.ndtvimg.com/i/2017-02/aaloo-paratha_620x350_71485944630.jpg",
    desc: `One of the most loved breakfast. Parathas are paired with curd and pickles for great taste.`,
  },
  {
    id: 8,
    title: "Kashmiri Rajma",
    category: "lunch",
    price: "₹ 80.00",
    img: "https://i.ndtvimg.com/i/2016-06/rajma_625x350_51466508213.jpg",
    desc: `Rajma is a popular Indian curry made with kidney beans. This recipe is made with aroma of Kashmiri garam masala and a host of other spices. `,
  },
  {
    id: 9,
    title: "Chocolate Hazelnut",
    category: "shakes",
    price: "₹ 70.00",
    img: "https://i.ndtvimg.com/i/2016-11/m_620x350_61480077157.jpg",
    desc: `Blend a creamy concoction with flavours of chocolate, cocoa powder and hazelnut. Garnish with hazelnuts, and chocolate shavings.`,
  },
  {
    id: 10,
    title: "Vada Paav",
    category: "breakfast",
    price: "₹ 30.00",
    img: "https://c.ndtvimg.com/2021-09/iptadnn8_vada-pav_625x300_23_September_21.jpg",
    desc: `The most popular food from Mumbai, It is sandwiched between slices of a Pav along with a generous amount of sweet and spicy chutneys.`,
  },
  {
    id: 12,
    title: "Dosa",
    category: "breakfast",
    price: "₹ 50.00",
    img: "https://c.ndtvimg.com/2020-06/spbf80l_breakfast_625x300_05_June_20.jpg",
    desc: `Imagine a flavourful filling, wrapped in a soft and crispy Indian-style crepe that gives you delicious taste.`,
  },
  {
    id: 11,
    title: "Idli",
    category: "breakfast",
    price: "₹ 30.00",
    img: "https://i.ndtvimg.com/i/2015-06/oats-idli_625x350_81434226005.jpg",
    desc: `Light up your boring mornings with this easy to cook and extremely healthy low calorie oats idli.`,
  },
  {
    id: 13,
    title: "Shahi Egg Curry",
    category: "lunch",
    price: "₹ 100.00",
    img: "https://i.ndtvimg.com/i/2017-11/goan-egg-curry_620x350_41511515276.jpg",
    desc: `Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt and fresh coriander.`,
  },
];
export default menu;
